// Echte Rohausgaben von Claude (claude-sonnet-5) aus dem US-Lauf, 08./09.10.2026,
// 1:1 aus stock_analyses.chart_data.swot bzw. app_events.details.tool_input
// uebernommen. Enthalten keine Schluessel oder Nutzerdaten.

export const RAW_SWOT_EXR = "{\n\"staerken\":[\"GroÃŸes, breit gestreutes Portfolio mit fast 1.900 Standorten in den USA\",\"Stabile, wiederkehrende Mieteinnahmen durch Vertragsstruktur\",\"Etabliertes, einfaches GeschÃ¤ftsmodell im Self-Storage-Segment\",\"S&P 500 Mitgliedschaft signalisiert GrÃ¶ÃŸe und StabilitÃ¤t\"],\n\"schwaechen\":[\"Keine internationale Diversifikation, reine US-Fokussierung\",\"Fehlende Transparenz zu Management-Historie und Insider-Aktienbesitz\",\"ZinssensitivitÃ¤t als REIT belastet Bewertung in Hochzinsphasen\"],\n\"chancen\":[\"Wachsender Bedarf an LagerflÃ¤chen durch UmzÃ¼ge, Downsizing und E-Commerce\",\"Konsolidierung im fragmentierten Self-Storage-Markt durch ZukÃ¤ufe mÃ¶glich\",\"DividendenattraktivitÃ¤t fÃ¼r einkommensorientierte Investoren\"],\n\"risiken\":[\"Steigende Zinsen kÃ¶nnten REIT-Bewertungen und Finanzierungskosten belasten\",\"Konjunkturabschwung kÃ¶nnte Nachfrage nach ZusatzlagerflÃ¤chen dÃ¤mpfen\",\"Starker Wettbewerb durch Peers wie Public Storage und CubeSmart\"]\n},\n\"fazit\":\"Extra Space Storage zeigt ein solides, gut verstÃ¤ndliches GeschÃ¤ftsmodell mit stabilen, wiederkehrenden UmsÃ¤tzen und starker Marktstellung im US-Self-Storage-Sektor, was sich im moderaten Fundamental-Score von rund 67 widerspiegelt. Die KrisenstabilitÃ¤t ist mit knapp 34 Punkten deutlich schwÃ¤cher ausgeprÃ¤gt, da das GeschÃ¤ft stark von Zinsniveau und US-Immobilienmarkt abhÃ¤ngt und keine geografische Diversifikation besteht. Mangels verfÃ¼gbarer Informationen zu Management-Historie, CEO-Aktienbesitz und Kapitalallokation bleibt die Governance-Bewertung lÃ¼ckenhaft und erfordert weitere Recherche. Die positive Kurs- und Nachrichtenentwicklung (Trend ca. 88) deutet auf aktuelles Marktvertrauen hin, die GesamteinschÃ¤tzung sollte dennoch konservativ und mit Vorbehalt hinsichtlich Zinsrisiken erfolgen.\"\n,\n\"firmenbeschreibung_de\":\"Extra Space Storage ist ein selbstverwalteter US-Immobilien-Investmentfonds (REIT) mit Sitz in Salt Lake City, der im S&P 500 gelistet ist. Das Unternehmen betreibt rund 1.900 Self-Storage-Anlagen in 40 US-Bundesstaaten, Washington D.C. und Puerto Rico mit insgesamt etwa 1,4 Millionen Lagereinheiten auf rund 147,5 Millionen QuadratfuÃŸ FlÃ¤che. Neben klassischen LagerrÃ¤umen bietet das Unternehmen spezialisierte StellplÃ¤tze fÃ¼r Boote, Wohnmobile und GeschÃ¤ftskunden an.\"\n}";

export const RAW_SWOT_FAST = "{\"staerken\":[\"Einfaches, verstaendliches Distributionsgeschaeft mit breiter Produktpalette\",\"Starkes Vertriebs- und Vending-Netzwerk als Wettbewerbsvorteil\",\"Lange, durchgehend profitable Unternehmenshistorie seit 1987\",\"Solide Dividendenpolitik und Kapitalallokation\"],\"schwaechen\":[\"Starke Abhaengigkeit vom nordamerikanischen Markt\",\"Kein klassisches Abo-Modell, Umsatz teils zyklisch\",\"Fehlende Transparenz zu CEO-Historie und Aktienbesitz\"],\"chancen\":[\"Weitere Expansion internationaler Maerkte moeglich\",\"Ausbau digitaler Vending- und Onsite-Loesungen staerkt Kundenbindung\",\"Konsolidierung im fragmentierten Industriedistributionsmarkt\"],\"risiken\":[\"Konjunkturabschwung in Industrie und Bau trifft Nachfrage direkt\",\"Wettbewerbsdruck durch groessere Peers wie Grainger oder MSC\",\"Hohe Bewertung erfordert kontinuierlich starke operative Ergebnisse\"]},\"fazit\":\"Fastenal zeigt ein solides, gut verstaendliches Geschaeftsmodell mit starker Marktstellung und langer profitabler Historie, was sich in den hohen Fundamental- und Trend-Scores widerspiegelt. Die Krisenstabilitaet faellt mit rund 72 Punkten moderater aus, da das Geschaeft konjunkturabhaengig ist. Zur Unternehmensfuehrung fehlen wesentliche oeffentlich zugaengliche Informationen, weshalb mehrere Management-Kriterien nicht bewertbar sind. Insgesamt eine qualitativ solide, aber nicht voellig krisenresistente Aktie mit Bewertungsluecken im Management-Bereich.\"}";

export const RAW_SWOT_TEL = "{\n\"staerken\":[\"Breites, diversifiziertes Produktportfolio in Steckverbindern und Sensorik\",\"Globale Umsatzverteilung Ã¼ber mehrere Regionen\",\"Starke Marktposition und Skaleneffekte\",\"LangjÃ¤hrige, stabile UnternehmensfÃ¼hrung\"],\n\"schwaechen\":[\"Keine wiederkehrenden Abo-UmsÃ¤tze\",\"Starke AbhÃ¤ngigkeit von zyklischen EndmÃ¤rkten wie Automobil und Industrie\",\"Geringe Konsumentenbekanntheit der Produkte\"],\n\"chancen\":[\"Wachstum durch Elektrifizierung und Automatisierung in Automobil- und Industriebereich\",\"Ausbau im Bereich DatenkonnektivitÃ¤t und Sensorik fÃ¼r neue Technologien (z.B. KI-Infrastruktur)\",\"Diversifikation in margenstÃ¤rkere NischenmÃ¤rkte\"],\n\"risiken\":[\"Konjunkturabschwung in Automobil- oder Industriesektor trifft Umsatz direkt\",\"Rohstoffpreisschwankungen (Kupfer, Kunststoffe) belasten Margen\",\"Wettbewerbsdruck durch Peers wie Amphenol und Littelfuse\"]\n},";

// FE: swot-Block aus dem eingebetteten Text im fazit (Fangnetz verwarf ihn
// wegen des <!-- --> mitten im JSON).
export const RAW_SWOT_FE = "{\n\"staerken\": [\"Regionales Versorgungsmonopol mit hohem Burggraben\", \"Stabile, regulierte und wiederkehrende UmsÃ¤tze\", \"Diversifizierter Energiemix aus mehreren Erzeugungsarten\", \"Grundlegend krisenresistentes GeschÃ¤ftsmodell\"],\n\"schwaechen\": [\"Keine internationale Diversifikation, reines US-GeschÃ¤ft\", \"Historischer Bestechungsskandal (Ohio HB6) belastet Reputation\", \"Hohe KapitalintensitÃ¤t und Investitionsbedarf ins Netz\", \"Begrenzte Transparenz zu Management-Historie (CEO-Daten unbekannt)\"],\n<!-- -->\n\"chancen\": [\"Wachsender Strombedarf durch Elektrifizierung und Rechenzentren\", \"Investitionen in Netzmodernisierung (T&D) kÃ¶nnten regulatorisch honoriert werden\", \"Erneuerbare-Energien-Ausbau (RECs, Wind/Solar) als Wachstumsfeld\"],\n\"risiken\": [\"Regulatorische Eingriffe und politische Risiken in KernmÃ¤rkten\", \"ZinssensitivitÃ¤t durch hohe Verschuldung\", \"Reputationsrisiko durch Nachwirkungen des HB6-Skandals\", \"Wetterbedingte InfrastrukturschÃ¤den und Investitionsdruck\"]\n}";
